Repository RibirX/Ribir, pull requests merged in 2025-03, with the labels that each got.

#704 fix(core): 🐛 enables embedding declare template as child in widget with Vec of template
  CHANGELOG.md
  core/src/builtin_widgets.rs
  core/src/widget_children/compose_child_impl.rs
  macros/src/child_template.rs
Labels: B-test

#705 fix(core): prevent panic in visual_box layout code
  core/src/builtin_widgets/background.rs
  core/src/builtin_widgets/border.rs
  core/src/builtin_widgets/clip_boundary.rs
  core/src/builtin_widgets/fitted_box.rs
  core/src/builtin_widgets/image_widget.rs
  core/src/builtin_widgets/padding.rs
  core/src/builtin_widgets/svg.rs
  core/src/builtin_widgets/transform_widget.rs
  themes/material/src/state_layer.rs
  widgets/src/divider.rs
  widgets/src/icon.rs
  widgets/src/input/text_glyphs.rs
  widgets/src/progress.rs
  widgets/src/transform_box.rs
Labels: B-test

#709 feat(core): 🎸 Add support for ColorFilter
  CHANGELOG.md
  core/src/builtin_widgets.rs
  core/src/builtin_widgets/color_filter.rs
  core/src/widget_tree/widget_id.rs
  gpu/src/gpu_backend.rs
  gpu/src/lib.rs
  gpu/src/wgpu_impl/shaders.rs
  painter/src/color.rs
  painter/src/painter.rs
  painter/src/svg.rs
  test_cases/ribir_core/builtin_widgets/color_filter/tests/default_text_with_default_by_wgpu.png
  test_cases/ribir_core/builtin_widgets/color_filter/tests/default_text_with_material_by_wgpu.png
Labels: B-test

#714 refactor(widgets): 💡 💡 Utilize the `Class` to implement `Avatar`
  CHANGELOG.md
  core/src/builtin_widgets/class.rs
  core/src/builtin_widgets/container.rs
  examples/messages/src/messages.rs
  examples/storybook/src/storybook.rs
  test_cases/ribir_widgets/avatar/tests/label_avatar_with_default_by_wgpu.png
  test_cases/ribir_widgets/avatar/tests/label_avatar_with_material_by_wgpu.png
  test_cases/ribir_widgets/avatar/tests/widget_avatar_with_default_by_wgpu.png
  test_cases/ribir_widgets/avatar/tests/widget_avatar_with_material_by_wgpu.png
  themes/material/src/classes.rs
  themes/material/src/classes/avatar_cls.rs
  themes/material/src/classes/buttons_cls.rs
  themes/material/src/classes/divider_cls.rs
  themes/material/src/classes/progress_cls.rs
  themes/material/src/lib.rs
  widgets/src/avatar.rs
  widgets/src/lists.rs
Labels: B-merge-ready, B-pr-num

#718 refactor(core): 💡 make `ColorFilter` to be a `WrapRender`
  .github/workflows/pr-num.yml
  core/src/builtin_widgets/color_filter.rs
Labels: B-pr-num

#719 refactor(widgets): 💡 `Tab` syntax
  .github/workflows/pr-num.yml
  docs/en/practice_todos_app/develop_a_todos_app.md
  docs/zh/practice_todos_app/develop_a_todos_app.md
  examples/messages/src/messages.rs
  examples/storybook/src/storybook.rs
  examples/todos/src/ui.rs
  widgets/src/icon.rs
  widgets/src/tabs.rs
Labels: B-merge-ready, B-pr-num

#721 refactor(widgets): 💡 Add support declare syntax for `Leading` and `Traling`
  macros/src/child_template.rs
  widgets/src/common_widget.rs
Labels: B-pr-num

#725 feat(core): 🎸 add non-child field support to `Template`
  CHANGELOG.md
  core/src/widget_children.rs
  macros/src/child_template.rs
  macros/src/simple_declare_attr.rs
  macros/src/util.rs
Labels: B-pr-num
